#!/usr/bin/env python3
"""Daily pipeline orchestrator: autonomous Scan → Match → Build → Apply → Outreach.

Runs the complete daily cycle end-to-end. Each phase feeds into the next:
  - Scan discovers new jobs from ATS APIs
  - Match scores them against the rubric, qualifies top matches
  - Build generates cover letters, wires blocks/resumes, auto-advances entries
  - Apply checks readiness and submits via ATS portals
  - Outreach generates follow-up templates and schedules protocol dates

Usage:
    python scripts/daily_pipeline_orchestrator.py                  # Full cycle, dry-run
    python scripts/daily_pipeline_orchestrator.py --yes            # Execute full cycle
    python scripts/daily_pipeline_orchestrator.py --phase scan     # Scan only
    python scripts/daily_pipeline_orchestrator.py --phase match    # Match only
    python scripts/daily_pipeline_orchestrator.py --phase build    # Build only
    python scripts/daily_pipeline_orchestrator.py --phase apply    # Apply only
    python scripts/daily_pipeline_orchestrator.py --phase outreach # Outreach only
    python scripts/daily_pipeline_orchestrator.py --json           # Machine-readable
"""

import argparse
import json
import sys
import time
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from apply_engine import apply_ready_entries
from match_engine import match_and_rank
from material_builder import build_materials
from outreach_engine import prepare_outreach
from scan_orchestrator import scan_all

ALL_PHASES = ["scan", "match", "build", "apply", "outreach"]


def _advance_built_entries(entry_ids: list[str], dry_run: bool = True) -> dict:
    """Auto-advance entries after materials are built.

    - qualified → drafting (materials generation started)
    - drafting → staged (materials wired, ready for review)

    Returns summary dict of advancements made.
    """
    if dry_run or not entry_ids:
        return {"advanced": [], "errors": []}

    from pipeline_lib import load_entry_by_id

    advanced = []
    errors = []

    for eid in entry_ids:
        filepath, entry = load_entry_by_id(eid)
        if not filepath or not entry:
            continue

        current = entry.get("status", "")
        target = None
        reason = None

        if current == "qualified":
            target = "drafting"
            reason = "materials generated by daily cycle"
        elif current == "drafting":
            # Check if enough materials are wired to advance to staged
            submission = entry.get("submission") or {}
            has_blocks = bool(submission.get("blocks_used"))
            variant_ids = submission.get("variant_ids") or {}
            has_cover = bool(variant_ids.get("cover_letter"))
            if has_blocks and has_cover:
                target = "staged"
                reason = "materials complete, auto-staged by daily cycle"

        if target:
            try:
                from advance import advance_entry
                ok = advance_entry(Path(filepath), eid, target, reason=reason)
                if ok:
                    advanced.append({"entry_id": eid, "from": current, "to": target})
            except Exception as e:
                errors.append(f"{eid}: advance {current}→{target} failed: {e}")

    return {"advanced": advanced, "errors": errors}


def _log_follow_up_actions(entry_ids: list[str], dry_run: bool = True) -> int:
    """Auto-log outreach template generation as follow-up actions on entries.

    This bridges the gap between outreach_engine (generates templates) and
    followup.py (tracks actions). Without this, entries block at the
    'outreach required' gate in apply_engine.
    """
    if dry_run or not entry_ids:
        return 0

    from datetime import date

    from pipeline_lib import load_entry_by_id

    logged = 0
    for eid in entry_ids:
        filepath, entry = load_entry_by_id(eid)
        if not filepath or not entry:
            continue

        try:
            from yaml_mutation import YAMLEditor
        except ImportError:
            break

        content = Path(filepath).read_text()
        editor = YAMLEditor(content)

        # Add an outreach action to satisfy the apply_engine gate
        follow_up = entry.get("follow_up") or {}
        actions_log = follow_up.get("actions_log") or []
        actions_log.append({
            "date": date.today().isoformat(),
            "channel": "linkedin",
            "type": "connect",
            "note": "Outreach templates generated by daily cycle",
            "auto": True,
        })
        editor.set("follow_up.actions_log", actions_log)
        editor.touch()
        Path(filepath).write_text(editor.dump())
        logged += 1

    return logged


def preflight_check() -> dict:
    """Verify the system is configured for autonomous operation.

    Returns dict with status and any missing prerequisites.
    """
    issues = []
    SCRIPTS_DIR = Path(__file__).resolve().parent
    REPO_ROOT = SCRIPTS_DIR.parent

    # Check submit config
    submit_config = SCRIPTS_DIR / ".submit-config.yaml"
    if not submit_config.exists():
        issues.append("missing .submit-config.yaml (personal info for ATS submission)")

    # Check blocks directory
    blocks_dir = REPO_ROOT / "blocks"
    if not blocks_dir.exists() or not list(blocks_dir.rglob("*.md")):
        issues.append("no blocks found in blocks/ directory")

    # Check scoring rubric
    rubric = REPO_ROOT / "strategy" / "scoring-rubric.yaml"
    if not rubric.exists():
        issues.append("missing strategy/scoring-rubric.yaml")

    # Check for at least some pipeline entries
    from pipeline_lib import ALL_PIPELINE_DIRS, load_entries
    entries = load_entries(dirs=ALL_PIPELINE_DIRS)
    if not entries:
        issues.append("no pipeline entries found")

    return {
        "ready": len(issues) == 0,
        "issues": issues,
        "entries_found": len(entries) if entries else 0,
    }


def run_daily_cycle(
    dry_run: bool = True,
    phases: list[str] | None = None,
) -> dict:
    """Run the complete daily Scan → Match → Build → Apply → Outreach cycle.

    Each phase feeds results forward:
      - Scan → new entry IDs → Match
      - Match → qualified IDs → Build
      - Build → built IDs → auto-advance → Apply
      - Apply → submitted IDs → Outreach
      - Outreach → follow-up actions logged

    Args:
        dry_run: If True, don't write any files.
        phases: Which phases to run. None = all.
    """
    if phases is None:
        phases = ALL_PHASES

    results: dict = {}
    scan_result = None
    match_result = None
    apply_result = None

    if "scan" in phases:
        scan_result = scan_all(dry_run=dry_run)
        results["scan"] = asdict(scan_result)

    if "match" in phases:
        entry_ids = scan_result.new_entries if scan_result else None
        match_result = match_and_rank(
            entry_ids=entry_ids,
            dry_run=dry_run,
        )
        results["match"] = asdict(match_result)

    if "build" in phases:
        qualified_ids = match_result.qualified if match_result else None
        build_result = build_materials(
            entry_ids=qualified_ids,
            dry_run=dry_run,
        )
        results["build"] = asdict(build_result)

        # Auto-advance entries after materials are built
        if build_result.entries_processed:
            advance_summary = _advance_built_entries(
                build_result.entries_processed, dry_run=dry_run,
            )
            results["auto_advance"] = advance_summary

    if "apply" in phases:
        apply_result = apply_ready_entries(dry_run=dry_run)
        results["apply"] = asdict(apply_result)

    if "outreach" in phases:
        submitted_ids = apply_result.submitted if apply_result else None
        outreach_result = prepare_outreach(
            entry_ids=submitted_ids,
            dry_run=dry_run,
        )
        results["outreach"] = asdict(outreach_result)

        # Auto-log follow-up actions so entries satisfy the outreach gate
        if outreach_result.entries_processed:
            logged = _log_follow_up_actions(
                outreach_result.entries_processed, dry_run=dry_run,
            )
            results["followup_actions_logged"] = logged

    return results


def main():
    parser = argparse.ArgumentParser(
        description="Daily pipeline: Scan → Match → Build → Apply → Outreach"
    )
    parser.add_argument("--yes", action="store_true", help="Execute full cycle")
    parser.add_argument(
        "--phase",
        action="append",
        choices=ALL_PHASES,
        help="Phase to run. Repeatable.",
    )
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument(
        "--preflight", action="store_true",
        help="Check system readiness without running",
    )
    args = parser.parse_args()

    if args.preflight:
        check = preflight_check()
        if args.json:
            print(json.dumps(check, indent=2))
        else:
            status = "READY" if check["ready"] else "NOT READY"
            print(f"\nPREFLIGHT CHECK: {status}")
            print(f"Entries found: {check['entries_found']}")
            if check["issues"]:
                print("\nIssues:")
                for issue in check["issues"]:
                    print(f"  - {issue}")
        sys.exit(0 if check["ready"] else 1)

    dry_run = not args.yes
    phases = args.phase  # None means all

    start = time.time()
    result = run_daily_cycle(dry_run=dry_run, phases=phases)
    elapsed = time.time() - start

    if args.json:
        result["_duration_seconds"] = round(elapsed, 1)
        print(json.dumps(result, indent=2, default=str))
    else:
        mode = "DRY-RUN" if dry_run else "EXECUTED"
        print(f"\n{'=' * 60}")
        print(f"DAILY PIPELINE CYCLE ({mode}) — {elapsed:.1f}s")
        print(f"{'=' * 60}")
        if "scan" in result:
            s = result["scan"]
            print(
                f"\n[SCAN] Fetched {s['total_fetched']}, "
                f"new {s['total_qualified']}, "
                f"dupes {s['duplicates_skipped']}"
            )
        if "match" in result:
            m = result["match"]
            print(
                f"[MATCH] Scored {m['entries_scored']}, "
                f"qualified {len(m['qualified'])} "
                f"(threshold {m['threshold_used']})"
            )
        if "build" in result:
            b = result["build"]
            print(
                f"[BUILD] Processed {len(b['entries_processed'])}, "
                f"letters {b['cover_letters_generated']}, "
                f"resumes tailored {b.get('resumes_tailored', 0)}, "
                f"resumes wired {b['resumes_wired']}"
            )
        if "auto_advance" in result:
            aa = result["auto_advance"]
            if aa["advanced"]:
                print(f"[ADVANCE] Auto-advanced {len(aa['advanced'])} entries:")
                for adv in aa["advanced"]:
                    print(f"  {adv['entry_id']}: {adv['from']} → {adv['to']}")
        if "apply" in result:
            a = result["apply"]
            print(
                f"[APPLY] Checked {len(a['checked'])}, "
                f"submitted {len(a['submitted'])}, "
                f"skipped {len(a['skipped'])}"
            )
        if "outreach" in result:
            o = result["outreach"]
            print(
                f"[OUTREACH] Entries {len(o['entries_processed'])}, "
                f"templates {o['templates_generated']}, "
                f"followups {o['followup_dates_set']}"
            )
        if "followup_actions_logged" in result:
            print(f"[FOLLOWUP] Auto-logged {result['followup_actions_logged']} actions")


if __name__ == "__main__":
    main()
