"""Shared constants for score.py."""

from __future__ import annotations

# High-prestige organizations — tiered by acceptance rate / selectivity.
# Tier 1 (~1-2% acceptance): 10  Tier 2 (~3-5%): 9  Tier 3 (~5-10%): 8  Others: 7-5
HIGH_PRESTIGE = {
    # Tier 1 — extremely competitive (≤2% acceptance)
    "Whiting Foundation": 10,
    "Creative Capital": 10,
    # Tier 2 — highly competitive (≤5% acceptance)
    "Doris Duke Charitable Foundation": 9,
    "LACMA": 9,
    "Prix Ars Electronica": 9,
    "Tulsa Artist Fellowship": 9,
    "Rauschenberg Foundation": 9,
    "Watermill Center": 9,
    # Tier 3 — competitive (5-10% acceptance / very high prestige)
    "S+T+ARTS Prize": 8,
    "Google": 8,
    "Anthropic": 8,
    "Eyebeam": 8,
    "ZKM": 8,
    "Mistral": 7,
    "ElevenLabs": 7,
    "Perplexity": 7,
    "Cursor": 7,
    "Anysphere": 7,
    # Tier 4 — notable but more accessible
    "Pioneer Works": 7,
    "Headlands Center for the Arts": 7,
    "NEW INC": 7,
    "Cohere": 6,
    "Runway": 6,
    "HuggingFace": 6,
    "Hugging Face": 6,
    "Replit": 6,
    "Vercel": 6,
    "Scale AI": 6,
    "GitLab": 6,
    "Twilio": 6,
    "MongoDB": 6,
    "Grafana Labs": 6,
    "Netlify": 6,
    "Airtable": 6,
    "Lambda Literary": 6,
    "Processing Foundation": 6,
    "Together AI": 5,
    "Weights & Biases": 5,
    "Modal": 5,
    "Replicate": 5,
    "Elastic": 5,
    "PlanetScale": 5,
    "Resend": 5,
    "Neon": 5,
    "Warp": 5,
    # Expansion — notable companies from source pool
    "DeepMind": 10,
    "Databricks": 9,
    "Plaid": 9,
    "Coinbase": 9,
    "Palantir": 9,
    "Snowflake": 8,
    "Robinhood": 8,
    "Affirm": 8,
    "Anduril": 8,
    "Brex": 7,
    "Mercury": 7,
    "Rippling": 7,
    "Prefect": 7,
    "Sentry": 7,
    "LangChain": 7,
    "Sierra AI": 7,
    "Harvey AI": 7,
    "Cognition": 7,
    "Fivetran": 6,
    "Postman": 6,
    "Gusto": 6,
    "Lattice": 6,
    "Deel": 6,
    "Airbyte": 6,
    "Grammarly": 6,
    "Dropbox": 6,
    "Reddit": 6,
    "Discord": 6,
    "Asana": 6,
    "Duolingo": 6,
    "Wiz": 6,
    "Semgrep": 5,
    "Pinecone": 5,
    "Weaviate": 5,
    "Honeycomb": 5,
    "Tailscale": 5,
    "Clerk": 5,
    "Zapier": 5,
    "Raycast": 5,
}

# Title-based role-fit tiers for auto-sourced entries.
# Derived from manually-scored submitted entries.
ROLE_FIT_TIERS = [
    {
        "name": "tier-1-strong",
        "title_patterns": [
            "developer experience",
            "developer tools",
            "devtools",
            "devex",
            "developer relations",
            "devrel",
            "developer advocate",
            "developer community",
            "developer education",
            "developer enablement",
            "developer productivity",
            "developer platform",
            "dx engineer",
            "education engineer",
            "education platform",
            "technical writer",
            "documentation engineer",
            "docs engineer",
            "cli ",
            "client infrastructure",
            "agent sdk",
            "agentic",
            "ai agent",
            "ai platform",
            "ai orchestration",
            "mcp ",
            "model context protocol",
            "claude code",
            "code quality",
            "code review",
            "test platform",
            "test infrastructure",
            "testing platform",
            "sdk ",
            "api platform",
        ],
        "mission_alignment": 9,
        "evidence_match": 9,
        "track_record_fit": 7,
    },
    {
        "name": "tier-4-poor",
        "title_patterns": [
            "machine learning",
            "ml engineer",
            "reinforcement learning",
            "security",
            "cybersecurity",
            "data engineer",
            "data infrastructure",
            "databases",
            "ios",
            "android",
            "mobile",
            "accelerator",
            "compute efficiency",
            "networking",
            "encoding",
            "inference",
            "recruiting",
            "audiovisual",
            "account abuse",
            "safeguard",
            "people product",
            "human data",
            "windows",
            "hardware",
            "embedded",
            "flight software",
            "robotics",
            "mechanical",
            "electrical",
            "manufacturing",
            "supply chain",
            "procurement",
            "sourcing",
            "marketing",
            "sales",
            "account executive",
            "customer success",
            "operations analyst",
            "financial analyst",
        ],
        "mission_alignment": 3,
        "evidence_match": 2,
        "track_record_fit": 2,
    },
    {
        "name": "tier-3-weak",
        "title_patterns": [
            "forward deployed",
            "applied ai",
            "growth",
            "enterprise",
            "business technology",
            "public sector",
            "solutions architect",
        ],
        "mission_alignment": 5,
        "evidence_match": 4,
        "track_record_fit": 3,
    },
    {
        "name": "tier-2-moderate",
        "title_patterns": [
            "software engineer",
            "full stack",
            "fullstack",
            "frontend",
            "backend",
            "platform engineer",
            "infrastructure engineer",
            "solutions engineer",
            "integrations",
            "product engineer",
            "site reliability",
        ],
        "mission_alignment": 7,
        "evidence_match": 6,
        "track_record_fit": 5,
    },
]

